import { PipelineListItem } from "src/app/shared/models/pipeline";

export const pipelineList: PipelineListItem[] = [
  {
    fundName: 'Hahn & Company II',
    gpName: 'Hahn & Company',
    interest: 'medium',
    phase: '2 Pager/Information',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Crestview IV',
    gpName: 'Crestview',
    interest: 'high',
    phase: 'Phase I',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['MSP', 'NYT']
  },
  {
    fundName: 'TPG VII',
    gpName: 'TPG',
    interest: 'low',
    phase: 'Phase II',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'New Horizon III',
    gpName: undefined,
    interest: 'medium',
    phase: 'Phase III',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Stockwell III',
    gpName: undefined,
    interest: 'high',
    phase: 'Phase II+',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Global Infrastructure Solution',
    gpName: undefined,
    interest: 'medium',
    phase: 'GIC',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Aquiline Financial Service',
    gpName: 'Hahn & Company',
    interest: 'medium',
    phase: 'IAC',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Crestview III',
    gpName: 'Crestview',
    interest: 'high',
    phase: 'Post IAC',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Equistone Europe V',
    gpName: undefined,
    interest: 'medium',
    phase: 'Closing',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Clessidra III',
    gpName: 'Clessidra',
    interest: 'low',
    phase: 'Syndication',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'New Horizon III',
    gpName: undefined,
    interest: 'medium',
    phase: 'Completed',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  },
  {
    fundName: 'Crestview IV',
    gpName: 'Crestview',
    interest: 'high',
    phase: 'Declined',
    ddLevel: 'Deep DD',
    expectedStartDate: '30-06-2020',
    expectedCloseDate: '31-12-2020',
    targetFundSize: 0,
    ccy: 'EUR',
    initialTargetAllocation: 0,
    overSubscribed: undefined,
    region: 'Asia',
    mainRegionFocus: 'Asia',
    country: 'Japan',
    allocations: ['SZO']
  }
]